name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build server
        run: npm run build

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Discord Webhook Notify
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify on Success
        if: ${{ success() }}
        run: echo "Success!"
